### ISSUE TITLE
Lavalamp Breaks with new query 3.1.0

### ISSUE THREAD

**Issue by llewcellist** [Richard1320/Lava-Lamp#10]
Dear Richard1320,

When I updated to jquery 3.1.0 on my website, the lava lamp plugin broke. Do you know of a patch for that? 

Thanks,
llewcellist

**Comment by Richard1320** [comment]
Hi llewcellist,

Thanks for informing me of the issue. After reviewing the problem, it seems that jQuery 3.1.0 is incompatible with easing 1.3. The author of that plugin has released a new version that works with both lavalamp and the latest version of jQuery. You need to download the easing plugin 1.4 from https://github.com/gdsmith/jquery.easing. The lavalamp plugin can stay the same.

Thanks,
Richard Hung

**Comment by llewcellist** [comment]
Dear Richard,

Thanks for your quick response. You are correct. The issue was with easing and some old scripts on my website that I was able to update. The lava lamp plugin was actually perfect.

Best wishes,
llewcellist
