### ISSUE TITLE
LL and LESS

### ISSUE THREAD

**Issue by intellilogic** [Richard1320/Lava-Lamp#11]
Because LL is ready before LESS has finished rendering the page, the lavalamp-object is often out of place.
Here’s the solution i placed in a later JS file:
`if(less||false){ less.pageLoadFinished.then(function(){ $('.lavalamp .active').mouseover() }) }`

**Comment by Richard1320** [comment]
You can also run the update method with `$('.lavalamp').lavalamp('update');`

**Comment by intellilogic** [comment]
`if(less||false){ less.pageLoadFinished.then(function(){ $('.lavalamp').lavalamp('update') }) }`
