### ISSUE TITLE
zIndex

### ISSUE THREAD

**Issue by intellilogic** [Richard1320/Lava-Lamp#8]
The items.addClass('lavalamp-item').css({ zIndex ..}) was causing problems for me.  I imagine this could cause problems for others.  I tried shifting my other z-indexes around so I wouldn’t have the change the JS; but then the behavior of ‘lavalamp-object’ became erratic.  I ended up removing items.addClass('lavalamp-item').css in the 2 places all together.

My setup was ‘menu > li > a’ and I have ‘lavalamp- object’ over ‘li’ under ‘a’ and it looks really nice.  Feature request 1: an option to turn off 'lavalamp-item' css
Feature request 2: delay before return.

**Comment by Richard1320** [comment]
1. This request is too case-specific. The z-index sometimes causes the lavalamp-object to go above the lavalamp-item. Absolute positioning is funny with its indexes. If it doesn't work, you can use CSS with ```.lavalamp-item{z-index: auto !important;}``` which will override the inline style.
2. Updated the plugin to 1.0.7 which adds ```delayOn``` and ```delayOff``` as options.
